bot:
  name: ${BOT_NAME:VaulterixExchangeDataBot}
  token: ${BOT_TOKEN:6798957645:AAHQM74GjK4SyfKC64B58-1zNYE-OdMxlRQ}

info:
  login: ${INFO_LOGIN:noreply@mitrasoft.ru}
  password: ${INFO_PASSWORD:!changeMe1}
  url: ${URL_PATH:https://vdr.vaulterix.ru/}

service:
  file_info:
    uri: https://api.telegram.org/bot{token}/getFile?file_id={fileId}
  file_storage:
    uri: https://api.telegram.org/file/bot{token}/{filePath}